<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<BaseOutputPath>..</BaseOutputPath>
		<LangVersion>preview</LangVersion>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">WINDOWS</DefineConstants>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">LINUX</DefineConstants>
		<DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">MACOS</DefineConstants>
		<IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
		<IsLinux>$([MSBuild]::IsOSPlatform('Linux'))</IsLinux>
		<IsOSX>$([MSBuild]::IsOSPlatform('OSX'))</IsOSX>
		<RootNamespace>libLlamaCpp</RootNamespace>
	</PropertyGroup>

	<Target Name="DetectCuda" BeforeTargets="CMakeConfigure">
		<PropertyGroup>
			<CudaExists>false</CudaExists>
		</PropertyGroup>
		<Exec Condition="'$(IsWindows)'=='true'"
			  Command="where nvcc"
			  IgnoreExitCode="true">
			<Output TaskParameter="ExitCode" PropertyName="CudaCommandExitCode" />
		</Exec>
		<Exec Condition="'$(IsWindows)'!='true'"
			  Command="which nvcc"
			  IgnoreExitCode="true">
			<Output TaskParameter="ExitCode" PropertyName="CudaCommandExitCodeUnix" />
		</Exec>
		<PropertyGroup>
			<CudaExists Condition="$(IsWindows) and $(CudaCommandExitCode)==0">true</CudaExists>
			<CudaExists Condition="!$(IsWindows) and $(CudaCommandExitCodeUnix)==0">true</CudaExists>
		</PropertyGroup>
	</Target>

	<Target Name="CMakePrepareForBuild" BeforeTargets="PrepareForBuild;Clean" Condition="'$(NativeLibraries)'!='OFF'">
		<PropertyGroup>
			<CMakeBin>cmake</CMakeBin>
		</PropertyGroup>
		<PropertyGroup>
			<CMakeProject>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\..\llama.cpp'))</CMakeProject>
		</PropertyGroup>
	</Target>

	<Target Name="CMakeConfigure" BeforeTargets="Build" Condition="'$(NativeLibraries)'!='OFF'">
		<PropertyGroup>
			<CMakeCompilerFlags Condition="$(IsWindows)">-DCMAKE_CXX_FLAGS="/W0 /EHsc /w /D _MBCS" -DCMAKE_C_FLAGS="/W0 /w"</CMakeCompilerFlags>
			<CMakeCompilerFlags Condition="!$(IsWindows)">-DCMAKE_CXX_FLAGS=-w -DCMAKE_C_FLAGS=-w</CMakeCompilerFlags>
			<CMakeOptions Condition="$(IsWindows)">-DGGML_CCACHE=OFF</CMakeOptions>
			<GGML_CUDA Condition="'$(CudaExists)'=='true'">ON</GGML_CUDA>
			<GGML_CUDA Condition="'$(CudaExists)'!='true'">OFF</GGML_CUDA>
		</PropertyGroup>
		<!-- https://github.com/ggerganov/llama.cpp/pull/1827#issuecomment-1588722643 -->
		<Exec Command='$(CMakeBin) -DGGML_AVX=ON -DGGML_AVX2=ON -DGGML_CUDA=$(GGML_CUDA) -DLLAMA_ALL_WARNINGS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_SERVER=OFF -DLLAMA_BUILD_TESTS=OFF $(CMakeOptions) -S "$(CMakeProject)" -B "$(CMakeProject)" $(CMakeCompilerFlags)' />
	</Target>

	<Target Name="CMakeBuild" AfterTargets="CMakeConfigure" Condition="'$(NativeLibraries)'!='OFF'">
		<Exec Command='$(CMakeBin) --build "$(CMakeProject)" -j --config $(Configuration)' />
	</Target>

	<Target Name="CMakeCopyOutput" AfterTargets="CMakeBuild" Condition="'$(NativeLibraries)'!='OFF'">
		<PropertyGroup>
			<LibraryFileExtension Condition="$(IsWindows)">*.dll</LibraryFileExtension>
			<LibraryFileExtension Condition="!$(IsWindows)">lib*.so</LibraryFileExtension>
		</PropertyGroup>
		<ItemGroup>
			<LibraryFiles Include="$(CMakeProject)/bin/$(Configuration)/$(LibraryFileExtension)" />
			<LibraryFiles Include="$(CMakeProject)/src/$(LibraryFileExtension)" />
			<LibraryFiles Include="$(CMakeProject)/ggml/src/$(LibraryFileExtension)" />
		</ItemGroup>
		<Copy SourceFiles="@(LibraryFiles)" DestinationFolder="$(MSBuildProjectDirectory)/../$(Configuration)/$(MSBuildProjectName)" />
	</Target>

</Project>
